import "./globals.css";

import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import localFont from "next/font/local";

export const bague = localFont({
  src: "./pfbague-pro.otf",
  display: "swap",
});
const futura = localFont({
  src: "./futura.ttf",
  display: "swap",
});

const rootfont = localFont({
  src: "./root-font.woff2",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rootfont.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
